apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lpaldaoy3-go 
  janus-idp.io/tekton: lpaldaoy3-go
  backstage.io/kubernetes-id: lpaldaoy3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpaldaoy3-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml